Gif component ref:
const GifDisplay: React.FC<GifDisplayProps> = ({ base64Image, prompt }) => {
    const imageUrl = `data:image/jpeg;base64,${base64Image}`;
  
    const handleDownload = () => {
      const link = document.createElement('a');
      link.href = imageUrl;
      const safePrompt = prompt.replace(/[^a-z0-9]/gi, '_').toLowerCase();
      link.download = `${safePrompt.slice(0, 30) || 'generated'}-image.jpeg`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    };
  
    return (
      <div className="mt-2 p-2 border border-green-700 bg-green-900/20 rounded max-w-sm text-glow">
        <p className="mb-2 text-green-300">Generated image for: "{prompt}"</p>
        <img src={imageUrl} alt={prompt} className="w-full h-auto rounded object-cover" />
        <button
          onClick={handleDownload}
          className="mt-2 w-full bg-green-600 hover:bg-green-500 text-black font-bold py-1 px-2 rounded transition-colors duration-200"
        >
          Download Image
        </button>
      </div>
    );
  };
  
---------------
Generate Image ref:
export const generateImage = async (prompt: string): Promise<string> => {
    if (!process.env.API_KEY) {
      console.error("API_KEY environment variable is not set.");
      throw new Error("API key is missing. Please configure your environment.");
    }
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
    try {
      const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: `A retro, pixelated, 8-bit gif style image of: ${prompt}`,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/jpeg',
          aspectRatio: '1:1',
        },
      });
  
      if (response.generatedImages && response.generatedImages.length > 0) {
        const base64ImageBytes = response.generatedImages[0].image.imageBytes;
        return base64ImageBytes;
      } else {
        throw new Error("No image was generated by the API.");
      }
    } catch (error) {
      console.error("Error generating image via Gemini API:", error);
      if (error instanceof Error) {
          return `Error: ${error.message}`;
      }
      throw new Error("Failed to generate image. The API returned an error.");
    }
  };
  