import { GoogleGenAI, Modality } from "@google/genai";

function getAiInstance(apiKey: string) {
  if (!apiKey) {
    throw new Error("API_KEY not provided");
  }
  return new GoogleGenAI({ apiKey: apiKey });
}

export type ImageModel = 'nano-banana' | 'imagen-4.0';

export async function generateImage(
  prompt: string, 
  apiKey: string, 
  aspectRatio: string = '1:1',
  model: ImageModel = 'nano-banana'
): Promise<string> {
  if (!apiKey) {
    throw new Error("API key is missing. Please configure your API key.");
  }

  // Validate aspect ratio format (should be like "1:1", "16:9", etc.)
  if (!/^\d+:\d+$/.test(aspectRatio)) {
    throw new Error(`Invalid aspect ratio format: "${aspectRatio}". Use format like "1:1", "16:9", "9:16", etc.`);
  }

  const ai = getAiInstance(apiKey);

  try {
    if (model === 'nano-banana') {
      // Nano Banana uses generateContent with Modality.IMAGE
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [{ text: prompt }],
        },
        config: {
          responseModalities: [Modality.IMAGE],
        },
      });

      // Extract image data from response
      if (response.candidates && response.candidates.length > 0) {
        const parts = response.candidates[0].content.parts;
        for (const part of parts) {
          if (part.inlineData) {
            return part.inlineData.data;
          }
        }
      }
      throw new Error("No image data found in the API response.");
    } else {
      // Imagen 4.0 uses generateImages
      const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/png',
          aspectRatio: aspectRatio as '1:1' | '16:9' | '9:16' | '4:3' | '3:4',
        },
      });

      if (response.generatedImages && response.generatedImages.length > 0) {
        const base64ImageBytes = response.generatedImages[0].image.imageBytes;
        return base64ImageBytes;
      } else {
        throw new Error("No image was generated by the API.");
      }
    }
  } catch (error) {
    console.error(`Error generating image via ${model} API:`, error);
    if (error instanceof Error) {
      throw new Error(`Failed to generate image: ${error.message}`);
    }
    throw new Error("Failed to generate image. The API returned an error.");
  }
}

