import { GoogleGenAI, Modality } from "@google/genai";
import type { GeminiUsageMetadata } from "./geminiService";
import { TokenCountService } from "./TokenCountService";

function getAiInstance(apiKey: string) {
  if (!apiKey) {
    throw new Error("API_KEY not provided");
  }
  return new GoogleGenAI({ apiKey: apiKey });
}

export type ImageModel = 'nano-banana' | 'imagen-4.0';

export interface ImageGenerationResult {
  imageData: string;
  usageMetadata?: GeminiUsageMetadata;
}

export async function generateImage(
  prompt: string,
  apiKey: string,
  aspectRatio: string = '1:1',
  model: ImageModel = 'nano-banana'
): Promise<ImageGenerationResult> {
  if (!apiKey) {
    throw new Error("API key is missing. Please configure your API key.");
  }

  // Validate aspect ratio format (should be like "1:1", "16:9", etc.)
  if (!/^\d+:\d+$/.test(aspectRatio)) {
    throw new Error(`Invalid aspect ratio format: "${aspectRatio}". Use format like "1:1", "16:9", "9:16", etc.`);
  }

  const ai = getAiInstance(apiKey);

  try {
    if (model === 'nano-banana') {
      const tokenCount = await TokenCountService.countTokensViaEndpoint(
        prompt,
        apiKey,
        'gemini-2.5-flash-image'
      );

      if (tokenCount > TokenCountService.NANO_BANANA_INPUT_LIMIT) {
        throw new Error(
          `Prompt exceeds Nano Banana token limit (${tokenCount.toLocaleString()} > ${TokenCountService.NANO_BANANA_INPUT_LIMIT.toLocaleString()}). Please shorten your prompt.`
        );
      }

      // Nano Banana uses generateContent with Modality.IMAGE
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [{ text: prompt }],
        },
        config: {
          responseModalities: [Modality.IMAGE],
        },
      });

      // Extract image data from response
      if (response.candidates && response.candidates.length > 0) {
        const parts = response.candidates[0].content.parts;
        for (const part of parts) {
          if (part.inlineData) {
            return {
              imageData: part.inlineData.data,
              usageMetadata: response.usageMetadata as GeminiUsageMetadata | undefined,
            };
          }
        }
      }
      throw new Error("No image data found in the API response.");
    } else {
      // Imagen 4.0 uses generateImages
      const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/png',
          aspectRatio: aspectRatio as '1:1' | '16:9' | '9:16' | '4:3' | '3:4',
        },
      });

      if (response.generatedImages && response.generatedImages.length > 0) {
        const base64ImageBytes = response.generatedImages[0].image.imageBytes;
        return {
          imageData: base64ImageBytes,
          usageMetadata: response.usageMetadata as GeminiUsageMetadata | undefined,
        };
      } else {
        throw new Error("No image was generated by the API.");
      }
    }
  } catch (error) {
    console.error(`Error generating image via ${model} API:`, error);
    if (error instanceof Error) {
      throw new Error(`Failed to generate image: ${error.message}`);
    }
    throw new Error("Failed to generate image. The API returned an error.");
  }
}

